# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: typos
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1.38.1
